name: CI/CD Pipeline

on:
    push:
        branches:
            - dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            # Step 3: Write .env.dev file dynamically from GitHub Secret
            - name: Create .env file
              run: |
                  echo ${{ secrets.DEV_ENV_FILE }} | base64 --decode > .env.dev

            # Step 4: Build the Docker image
            - name: Build Docker Image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-ts-ex-ch7 .

            # Step 5: Push Docker image to Docker Hub or ECR (optional)
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Push Docker Image
              run: |
                  docker tag ${{ secrets.DOCKER_USERNAME }}/dev-ts-ex-ch7 ${{ secrets.DOCKER_USERNAME }}/dev-ts-ex-ch7:dev
                  docker push ${{ secrets.DOCKER_USERNAME }}/dev-ts-ex-ch7:dev

            - name: composing
              run: |
                  mkdir dev-ts-ex-ch7-app
                  cp compose.yml dev-ts-ex-ch7-app/compose.yml
                  cd dev-ts-ex-ch7-app
                  docker-compose -H ${{ secrets.DOCKER_HOST }} pull
                  docker-compose -H ${{ secrets.DOCKER_HOST }} up -d
